name: OpenWrt 21.02 / armvirt-32

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    uses: ./.github/workflows/_compat-impl.yml
    with:
      image: ghcr.io/openwrt/rootfs:armvirt-32-v21.02.6
      platform: linux/arm/v7
