name: OpenWrt 22.03 / aarch64

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    uses: ./.github/workflows/_compat-impl.yml
    with:
      image: ghcr.io/openwrt/rootfs:aarch64_cortex-a53-v22.03.4
      platform: linux/arm64
