name: OpenWrt 21.02 / aarch64

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    uses: ./.github/workflows/_compat-impl.yml
    with:
      image: ghcr.io/openwrt/rootfs:aarch64_cortex-a53-v21.02.6
      platform: linux/arm64
