name: OpenWrt snapshot / mips_24kc

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    uses: ./.github/workflows/_compat-impl.yml
    with:
      image: ghcr.io/openwrt/rootfs:mips_24kc-master
      platform: linux/mips
