name: OpenWrt snapshot / arm_a15

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    uses: ./.github/workflows/_compat-impl.yml
    with:
      image: ghcr.io/openwrt/rootfs:arm_cortex-a15_neon-vfpv4-master
      platform: linux/arm/v7
